// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH7MC3HX9crgmyfJG4CUvlXpD21S7BrKI',
    appId: '1:245549996846:android:5dc6a81c1a78564fbfb8bf',
    messagingSenderId: '245549996846',
    projectId: 'instagram-clone-44873',
    storageBucket: 'instagram-clone-44873.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfjZmqrUoCcVH-IeKCpR_OJsXWM9mb5Lc',
    appId: '1:245549996846:ios:44db8ac9332a44abbfb8bf',
    messagingSenderId: '245549996846',
    projectId: 'instagram-clone-44873',
    storageBucket: 'instagram-clone-44873.appspot.com',
    androidClientId: '245549996846-4hi19udt26suu3qf4l75t9lrb5gdjnaf.apps.googleusercontent.com',
    iosClientId: '245549996846-9aioaq28jn0oqud8lp5fpk1c9vc4q08t.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseWhy',
  );
}
